# Generated by Django 3.0.3 on 2020-02-18 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'maincategories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=45)),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starbucks_menu.MainCategory')),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_image_url', models.URLField(max_length=500)),
                ('product_name', models.CharField(max_length=45)),
                ('product_name_english', models.CharField(max_length=300)),
                ('main_comment', models.CharField(max_length=500)),
                ('calories', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=4)),
                ('salt', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sugar', models.DecimalField(decimal_places=1, max_digits=4)),
                ('caffein', models.DecimalField(decimal_places=1, max_digits=4)),
                ('allegen_information', models.CharField(max_length=100)),
                ('small_image_url', models.URLField(max_length=500)),
                ('sub_comment', models.CharField(max_length=500)),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starbucks_menu.MainCategory')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starbucks_menu.SubCategory')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
