# Generated by Django 3.0.3 on 2020-02-18 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='allegen_information',
        ),
        migrations.CreateModel(
            name='ProductAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=45)),
                ('allergy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starbucks_menu.Allergy')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starbucks_menu.Product')),
            ],
            options={
                'db_table': 'product_allergies',
            },
        ),
    ]
