# Generated by Django 3.0.3 on 2020-02-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks_menu', '0002_auto_20200218_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='main_category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name_english',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='main_category_id',
            new_name='main_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category_id',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='productallergy',
            old_name='allergy_id',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='productallergy',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='main_category_id',
            new_name='main_category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='productallergy',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='product',
            name='main_comment',
            field=models.CharField(max_length=550),
        ),
    ]
