# Generated by Django 3.0.3 on 2020-02-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks_menu', '0004_auto_20200218_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'allergies2',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_allergy2',
            field=models.ManyToManyField(null=True, to='starbucks_menu.Allergy2'),
        ),
    ]
