# Generated by Django 3.0.3 on 2020-02-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks_menu', '0005_auto_20200218_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'size',
            },
        ),
    ]
