# Generated by Django 3.0.3 on 2020-02-20 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks_menu', '0006_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('salt', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('sugar', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('caffein', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'nutritions',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'products_sizes',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_allergy',
            new_name='allergy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='caffein',
        ),
        migrations.RemoveField(
            model_name='product',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_allergy2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sugar',
        ),
        migrations.AlterModelTable(
            name='productallergy',
            table='products_allergies',
        ),
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
        migrations.DeleteModel(
            name='Allergy2',
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starbucks_menu.Product'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starbucks_menu.Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='starbucks_menu.Nutrition'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(null=True, through='starbucks_menu.ProductSize', to='starbucks_menu.Size'),
        ),
    ]
